// This file has been generated by Specta. DO NOT EDIT.

export type Player = { id: number; x: number; y: number; name: string; team_id: number }

export type Train = { id: number; long: number; lat: number; line_id: string; direction: string }

export type GameState = { players: Player[]; trains: Train[] }

export type Line = { id: number; name: string; color: string }

export type ServerMessage = { GameState: GameState }

export type ClientMessage = { Position: { x: number; y: number } } | { Message: string }

export type Team = { id: number; name: string; color: string }

