name: CI

on:
  - pull_request
  - push

env:
  CARGO_TERM_COLOR: always

jobs:
  robusta:
    name: 🦀 robusta Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-robusta-mister-x

      - name: 🔬 Rust fmt
        run: cargo fmt --check --all

      - name: 🔨 Build robusta
        run: cargo build


  liberica:
    name: ⚡ liberica Check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: liberica

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: liberica/node_modules
          key: ${{ runner.os }}-liberica-mister-x

      - name: 🚧 Setup bun
        uses: oven-sh/setup-bun@v1

      - name: 🚧 Install dependencies
        run: bun install

      - name: 🔨 Build liberica
        run: bun run build

      - name: 🔎 Lint liberica
        run: bun lint
