name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            target
            liberica/node_modules
          key: ${{ runner.os }}-mister-x
      - name: Build liberica
        run: |
          cd liberica
          npm ci
          npm run build
      - name: Build robusta
        run: |
          cd robusta
          cargo build
