name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      
env:
  CARGO_TERM_COLOR: always

jobs:
  robusta:
    name: 🦀 robusta Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - name: Change directory
        run: cd robusta
        
      - uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-robusta-mister-x

      - name: 🚧 Build robusta
        run: cargo build
          
      - name: 🔬 Check formatting
        run: cargo fmt --all -- --check


  liberica:
    name: ⚡ liberica Check & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        
      - uses: actions/cache@v3
        with:
          path: liberica/node_modules
          key: ${{ runner.os }}-liberica-mister-x
        
      - name: 🚧 Setup bun
        uses: oven-sh/setup-bun@v1
        
      - name: Change directory
        run: cd liberica

      - name: 🚧 Install dependencies
        run: bun install

      - name: 🔎 Lint liberica
        run: bun lint
