name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            target
            liberica/node_modules
          key: ${{ runner.os }}-mister-x

      - uses: oven-sh/setup-bun@v1
      - name: Build liberica
        run: |
          cd liberica
          bun lint
          bun run build

      - name: Build robusta
        run: |
          cd robusta
          cargo build
